=== aaikinsm/FDM-Programs/HTMLExample/WebContent/subjects.dtd
<!-- 
	+ One or more occurrences  
	* Zero or more occurrences
	? Either 1 or nothing
	a, b    a followed by b
	a | b   a followed by b 
-->
<!ELEMENT documents (document*)>
<!ELEMENT document (title*, subjectID, subjectname, prerequisite?, classes, assessment, syllabus, textbooks*)>
<!ELEMENT prerequisite (subjectID, subjectname)>
<!ELEMENT textbooks (author+, booktitle)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subjectID (#PCDATA)>
<!ELEMENT subjectname (#PCDATA)>
<!ELEMENT classes (#PCDATA)>
<!ELEMENT assessment (#PCDATA)>
<!ATTLIST assessment assessment_type (exam | assignment) #IMPLIED> <!-- #REQUIRED: A value must be given. It may not be the empty string.   #IMPLIED: No value need to be given.  -->
<!ELEMENT syllabus (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT booktitle (#PCDATA)>

=== aaikinsm/FDM-Programs/HTMLExample/WebContent/document.xml
<?xml version="1.0" ?>

<!--define the location of the external DTD using a relative URL address -->
<!DOCTYPE document SYSTEM "subjects.dtd">

<documents>
	<document>
		<title>Artificial Intelligence</title>
		<subjectID>2.303</subjectID>
		<subjectname>Computer Science</subjectname>
		<prerequisite>
			<subjectID>1.001</subjectID>
			<subjectname>Algorithm Design</subjectname>
		</prerequisite>
		<classes>4 hours per week (lectures and tutorials) for one semester.</classes>
		<assessment assessment_type="exam">2hr exam at the end of the course.</assessment>
		<syllabus>
			AI theory.
		</syllabus>
		<textbooks>
			<author>Stuart J. Russell</author>
			<author>Peter Norvig</author>
			<booktitle>Artificial Intelligence: A Modern Approach</booktitle>
		</textbooks>
	</document>
	<document>
		<title>Introduction to Programming in Java</title>
		<subjectID>3.045</subjectID>
		<subjectname>Computer Science</subjectname>
		<prerequisite>
			<subjectID>1.021</subjectID>
			<subjectname>C++</subjectname>
		</prerequisite>
		<classes>4 hours per week (lectures and tutorials) for one semester.</classes>
		<assessment assessment_type="assignment">tutorial assignments.</assessment>
		<syllabus>
			Introduction to Java.
		</syllabus>
		<textbooks>
			<author>James Gosling</author>
			<booktitle>Java Programming Language 5th Edition</booktitle>
		</textbooks>
	</document>
</documents>
